sudo: required
services:
  - docker

language: python

branches:
  only:
    - master
    - development
    - /^.*release.*$/

python:
  - "3.6"


before_script:
  - docker build -t pdf2invoice -f docker-homolog .
  - docker run -d -p 8000:8000 --name pdf2invoice pdf2invoice
   

script:
  - docker exec pdf2invoice coverage erase
  - docker exec pdf2invoice coverage run --source='.' manage.py test
  - docker exec pdf2invoice coverage report
  - docker exec pdf2invoice flake8

after_script:
  - docker stop pdf2invoice

after_success: 
  - coveralls

deploy:
  - provider: script
    script: bash scripts/deploy.sh
    on:
      branch: development
  - provider: script
    script: bash scripts/sendZip.sh
    on:
      branch: master

addons:
  apt:
    packages:
      - docker-ce
