version: '3'

services:
  metabase:
    image: metabase/metabase:v0.23.1
    volumes:
      - ./mydatabase:/mydatabase
      - ./metabase.db.mv.db:/metabase.db.mv.db
    ports:
      - "3030:3000"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - metabase
